// frontend/uni-app/packages/modules/system/src/views/pagesMember/profile/profile.vue
<script setup lang="ts">
import { defAuthService } from '@liujitcn/kratos-uni-app-core/api/system/app/v1/auth'
import { useUserStore } from '@liujitcn/kratos-uni-app-core/stores'
import type { UserProfileForm } from '@liujitcn/kratos-uni-app-core/rpc/system/app/v1/auth'
import { onLoad } from '@dcloudio/uni-app'
import { computed, onBeforeUnmount, ref } from 'vue'
import type { BaseDictForm_DictItem } from '@liujitcn/kratos-uni-app-core/rpc/system/app/v1/base_dict'
import { BaseUserIDType } from '@liujitcn/kratos-uni-app-core/rpc/system/common/v1/common'
import { defBaseDictService } from '@liujitcn/kratos-uni-app-core/api/system/app/v1/base_dict'
import { formatSrc } from '@liujitcn/kratos-uni-app-core/utils/index'
import { uploadFile } from '@liujitcn/kratos-uni-app-core/utils/file'
import { navigateToLogin } from '@liujitcn/kratos-uni-app-core/utils/navigation'
import defaultAvatar from '@liujitcn/kratos-uni-app-core/static/images/avatar.png'
import navigatorBackground from '@liujitcn/kratos-uni-app-core/static/images/navigator_bg.png'
import { useI18n } from '@liujitcn/kratos-uni-app-core'

const userStore = useUserStore()
const { t } = useI18n()

// 获取屏幕边界到安全区域距离
const { safeAreaInsets } = uni.getSystemInfoSync()

const imgMaxSize = ref(1024 * 1024)
const submitting = ref(false)
let navigateBackTimer: ReturnType<typeof setTimeout> | undefined

onBeforeUnmount(() => {
  if (navigateBackTimer) clearTimeout(navigateBackTimer)
  navigateBackTimer = undefined
})

// 获取个人信息，修改个人信息需提供初始值
const userInfo = ref({} as UserProfileForm)
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
const idCodePattern = /^[A-Za-z0-9][A-Za-z0-9-]{0,63}$/
const idTypeOptions = computed(() => [
  {
    label: t('system.profile.id_type.unspecified'),
    value: BaseUserIDType.BASE_USER_ID_TYPE_UNSPECIFIED,
  },
  { label: t('system.profile.id_type.id_card'), value: BaseUserIDType.BASE_USER_ID_TYPE_ID_CARD },
  { label: t('system.profile.id_type.passport'), value: BaseUserIDType.BASE_USER_ID_TYPE_PASSPORT },
  {
    label: t('system.profile.id_type.hk_macao_permit'),
    value: BaseUserIDType.BASE_USER_ID_TYPE_HK_MACAO_PERMIT,
  },
  {
    label: t('system.profile.id_type.taiwan_permit'),
    value: BaseUserIDType.BASE_USER_ID_TYPE_TAIWAN_PERMIT,
  },
  {
    label: t('system.profile.id_type.foreign_permanent_residence'),
    value: BaseUserIDType.BASE_USER_ID_TYPE_FOREIGN_PERMANENT_RESIDENCE,
  },
  { label: t('system.profile.id_type.other'), value: BaseUserIDType.BASE_USER_ID_TYPE_OTHER },
])
const idTypeIndex = computed(() => {
  const index = idTypeOptions.value.findIndex((item) => item.value === userInfo.value.id_type)
  return index >= 0 ? index : 0
})
const idTypeLabel = computed(
  () => idTypeOptions.value[idTypeIndex.value]?.label || idTypeOptions.value[0].label,
)
const syncUserStoreProfile = (profile: UserProfileForm) => {
  if (!userStore.userInfo) {
    return
  }

  userStore.userInfo.user_name = profile.user_name
  userStore.userInfo.nick_name = profile.nick_name
  userStore.userInfo.gender = profile.gender
  userStore.userInfo.phone = profile.phone
  userStore.userInfo.avatar = profile.avatar
  userStore.userInfo.email = profile.email
  userStore.userInfo.id_type = profile.id_type
  userStore.userInfo.id_code = profile.id_code
}

const getUserData = async () => {
  const res = await defAuthService.GetUserProfile({})
  userInfo.value = res
  // 同步 Store 的头像和昵称，用于我的页面展示
  syncUserStoreProfile(res)
}

const genderList = ref<BaseDictForm_DictItem[]>([])

const getDictData = async () => {
  const genderCode = 'base_user_gender'
  const res = await defBaseDictService.GetBaseDict({
    code: genderCode,
  })
  genderList.value = res.items || []
}

onLoad(() => {
  if (!userStore.ensureAuthenticated()) {
    navigateToLogin()
    return
  }

  Promise.all([getUserData(), getDictData()])
})
// 修改头像
const onAvatarChange = async () => {
  if (!userStore.ensureAuthenticated()) {
    navigateToLogin()
    return
  }

  // 调用拍照/选择图片
  // 选择图片条件编译
  // #ifdef H5 || APP-PLUS
  // 微信小程序从基础库 2.21.0 开始， wx.chooseImage 停止维护，请使用 uni.chooseMedia 代替
  uni.chooseImage({
    count: 1,
    success: async (res: any) => {
      const { path, size } = res.tempFiles[0]
      if (size > imgMaxSize.value) {
        await uni.showToast({
          title: t('system.profile.photo_limit'),
          icon: 'none',
          duration: 1500,
        })
        return
      }
      // 上传
      await uploadAvatar(path)
    },
  })
  // #endif

  // #ifdef MP-WEIXIN
  // uni.chooseMedia 仅支持微信小程序端
  uni.chooseMedia({
    // 文件个数
    count: 1,
    // 文件类型
    mediaType: ['image'],
    success: async (res: any) => {
      // 本地路径
      const { tempFilePath, size } = res.tempFiles[0]
      if (size > imgMaxSize.value) {
        await uni.showToast({
          title: t('system.profile.photo_limit'),
          icon: 'none',
          duration: 1500,
        })
        return
      }
      await uploadAvatar(tempFilePath)
    },
  })
  // #endif
}

// 上传头像并同步个人资料与用户 Store。
const uploadAvatar = async (file: string) => {
  if (!userStore.ensureAuthenticated()) {
    navigateToLogin()
    return
  }

  try {
    const fileInfo = await uploadFile('avatar', file)
    userInfo.value.avatar = fileInfo.url
    await defAuthService.UpdateUserProfile({ user_profile: userInfo.value })
    syncUserStoreProfile(userInfo.value)
    await uni.showToast({ icon: 'success', title: t('system.profile.update_success') })
  } catch {
    await uni.showToast({ icon: 'error', title: t('system.profile.avatar_upload_failed') })
  }
}

// 修改性别
const onGenderChange: UniHelper.RadioGroupOnChange = (ev) => {
  userInfo.value.gender = Number(ev.detail.value)
}

// 选择证件类型。
const onIdTypeChange: UniHelper.SelectorPickerOnChange = (ev) => {
  userInfo.value.id_type =
    idTypeOptions.value[Number(ev.detail.value)]?.value ??
    BaseUserIDType.BASE_USER_ID_TYPE_UNSPECIFIED
}

// #ifdef MP-WEIXIN
// 新增授权手机号处理
const onGetPhoneNumber: UniHelper.ButtonOnGetphonenumber = async (e) => {
  if (e.detail.errMsg !== 'getPhoneNumber:ok') return
  if (!userStore.ensureAuthenticated()) {
    navigateToLogin()
    return
  }

  const res = await defAuthService.BindUserPhone({ code: e.detail.code || '' })
  userInfo.value.phone = res.phone
  syncUserStoreProfile(userInfo.value)
  await uni.showToast({ icon: 'success', title: t('system.profile.phone_authorization_success') })
}

// #endif

// 点击保存提交表单
const onSubmit = async () => {
  if (submitting.value) return
  if (!userStore.ensureAuthenticated()) {
    navigateToLogin()
    return
  }

  if (userInfo.value.email && !emailPattern.test(userInfo.value.email)) {
    await uni.showToast({ icon: 'none', title: t('system.profile.email_invalid') })
    return
  }
  if (userInfo.value.id_code && !idCodePattern.test(userInfo.value.id_code)) {
    await uni.showToast({ icon: 'none', title: t('system.profile.id_code_invalid') })
    return
  }

  submitting.value = true
  try {
    const { nick_name, gender, email, id_type, id_code } = userInfo.value
    await defAuthService.UpdateUserProfile({
      user_profile: {
        nick_name: nick_name,
        gender: gender,
        avatar: userInfo.value.avatar,
        phone: userInfo.value.phone,
        user_name: userInfo.value.user_name,
        email,
        id_type,
        id_code,
      },
    })
    // 更新Store昵称
    syncUserStoreProfile(userInfo.value)
    await uni.showToast({ icon: 'success', title: t('system.profile.save_success') })
    if (navigateBackTimer) clearTimeout(navigateBackTimer)
    navigateBackTimer = setTimeout(() => {
      navigateBackTimer = undefined
      uni.navigateBack()
    }, 400)
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <view class="viewport" :style="{ backgroundImage: `url(${navigatorBackground})` }">
    <!-- 导航栏 -->
    <view class="navbar" :style="{ paddingTop: safeAreaInsets?.top + 'px' }">
      <navigator open-type="navigateBack" class="back icon-left" hover-class="none"></navigator>
      <view class="title">{{ t('system.profile.title') }}</view>
    </view>
    <view class="avatar">
      <view @tap="onAvatarChange" class="avatar-content">
        <image
          v-if="userInfo?.avatar"
          class="image"
          :src="formatSrc(userInfo?.avatar)"
          mode="aspectFill"
        />
        <image v-else class="image" :src="defaultAvatar" mode="aspectFill"></image>
        <text class="text">{{ t('system.profile.avatar_change') }}</text>
      </view>
    </view>
    <!-- 表单 -->
    <view class="form">
      <!-- 表单内容 -->
      <view class="form-content">
        <view class="form-item" v-if="userInfo?.user_name">
          <text class="label">{{ t('system.profile.account') }}</text>
          <text class="account placeholder">{{ userInfo?.user_name }}</text>
        </view>
        <!-- #ifdef MP-WEIXIN -->
        <!-- 手机号 -->
        <view class="form-item">
          <text class="label">{{ t('system.profile.mobile') }}</text>
          <view class="input">
            <text v-if="userInfo.phone" class="account">{{ userInfo.phone }}</text>
            <button
              v-else
              class="auth-button"
              open-type="getPhoneNumber"
              @getphonenumber="onGetPhoneNumber"
            >
              {{ t('system.profile.phone_authorization') }}
            </button>
          </view>
        </view>
        <!-- #endif -->
        <view class="form-item">
          <text class="label">{{ t('system.profile.nick_name') }}</text>
          <input
            class="input"
            type="text"
            :placeholder="t('system.profile.nick_name_placeholder')"
            v-model="userInfo.nick_name"
          />
        </view>
        <view class="form-item">
          <text class="label">{{ t('system.profile.email') }}</text>
          <input
            class="input"
            type="text"
            :placeholder="t('system.profile.email_placeholder')"
            v-model="userInfo.email"
          />
        </view>
        <view class="form-item">
          <text class="label">{{ t('system.profile.id_type') }}</text>
          <picker
            class="picker"
            mode="selector"
            :range="idTypeOptions"
            range-key="label"
            :value="idTypeIndex"
            @change="onIdTypeChange"
          >
            <view class="input">{{ idTypeLabel }}</view>
          </picker>
        </view>
        <view class="form-item">
          <text class="label">{{ t('system.profile.id_code') }}</text>
          <input
            class="input"
            type="text"
            :placeholder="t('system.profile.id_code_placeholder')"
            v-model="userInfo.id_code"
          />
        </view>
        <view class="form-item">
          <text class="label">{{ t('system.profile.gender') }}</text>
          <radio-group @change="onGenderChange">
            <label class="radio" v-for="(item, index) in genderList" :key="index">
              <radio
                :value="item.value"
                color="#27ba9b"
                :checked="userInfo?.gender === Number(item.value)"
              />
              {{ item.label }}
            </label>
          </radio-group>
        </view>
      </view>
      <!-- 提交按钮 -->
      <button @tap="onSubmit" class="form-button">{{ t('common.action.save') }}</button>
    </view>
  </view>
</template>

<style lang="scss">
page {
  background-color: #f4f4f4;
}

.viewport {
  display: flex;
  flex-direction: column;
  height: 100%;
  min-height: 100vh;
  box-sizing: border-box;
  background-color: #f4f4f4;
  background-size: auto 420rpx;
  background-repeat: no-repeat;
}

// 导航栏
.navbar {
  position: relative;

  .title {
    height: 40px;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 16px;
    font-weight: 500;
    color: #fff;
  }

  .back {
    position: absolute;
    height: 40px;
    width: 40px;
    left: 0;
    font-size: 20px;
    color: #fff;
    display: flex;
    justify-content: center;
    align-items: center;

    &::before {
      content: '‹';
    }
  }
}

// 头像
.avatar {
  text-align: center;
  width: 100%;
  height: 260rpx;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;

  .image {
    width: 160rpx;
    height: 160rpx;
    border-radius: 50%;
    background-color: #eee;
  }

  .text {
    display: block;
    padding-top: 20rpx;
    line-height: 1;
    font-size: 26rpx;
    color: #fff;
  }
}

// 表单
.form {
  background-color: #f4f4f4;

  &-content {
    margin: 20rpx 20rpx 0;
    padding: 0 20rpx;
    border-radius: 10rpx;
    background-color: #fff;
  }

  &-item {
    display: flex;
    height: 96rpx;
    line-height: 46rpx;
    padding: 25rpx 10rpx;
    background-color: #fff;
    font-size: 28rpx;
    border-bottom: 1rpx solid #ddd;

    &:last-child {
      border: none;
    }

    .label {
      width: 180rpx;
      color: #333;
    }

    .account {
      color: #666;
    }

    .input {
      flex: 1;
      display: block;
      height: 46rpx;
    }

    .radio {
      margin-right: 20rpx;
    }

    .picker {
      flex: 1;
    }
    .placeholder {
      color: #808080;
    }
  }

  &-button {
    height: 80rpx;
    text-align: center;
    line-height: 80rpx;
    margin: 30rpx 20rpx;
    color: #fff;
    border-radius: 80rpx;
    font-size: 30rpx;
    background-color: #27ba9b;
  }
}
.auth-button {
  height: 60rpx;
  line-height: 60rpx;
  margin: 0;
  padding: 0 20rpx;
  font-size: 26rpx;
  color: #27ba9b;
  border: 1rpx solid #27ba9b;
  border-radius: 30rpx;
  background: none;

  &::after {
    border: none;
  }
}
</style>

// frontend/taro-app/packages/modules/system/src/views/pagesMember/profile/profile.tsx
import {
  Button,
  Image,
  Input,
  Label,
  Picker,
  Radio,
  RadioGroup,
  Text,
  View,
} from '@tarojs/components'
import Taro, { useLoad } from '@tarojs/taro'
import { useEffect, useRef, useState } from 'react'
import defaultAvatar from '@liujitcn/kratos-taro-app-core/static/images/avatar.png'
import navigatorBackground from '@liujitcn/kratos-taro-app-core/static/images/navigator_bg.png'
import { defAuthService } from '@liujitcn/kratos-taro-app-core/api/system/app/v1/auth'
import { defBaseDictService } from '@liujitcn/kratos-taro-app-core/api/system/app/v1/base_dict'
import type { BaseDictForm_DictItem } from '@liujitcn/kratos-taro-app-core/rpc/system/app/v1/base_dict'
import type { UserProfileForm } from '@liujitcn/kratos-taro-app-core/rpc/system/app/v1/auth'
import { BaseUserIDType } from '@liujitcn/kratos-taro-app-core/rpc/system/common/v1/common'
import {
  formatSrc,
  navigateToLogin,
  uploadFile,
  useI18n,
  useUserStore,
} from '@liujitcn/kratos-taro-app-core'
import './profile.scss'

const IMG_MAX_SIZE = 1024 * 1024
const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
const ID_CODE_PATTERN = /^[A-Za-z0-9][A-Za-z0-9-]{0,63}$/

/** 用户个人资料编辑页。 */
export default function ProfilePage() {
  const { locale, t } = useI18n()
  const [userInfo, setUserInfo] = useState<UserProfileForm>({
    user_name: '',
    nick_name: '',
    gender: 0,
    phone: '',
    email: '',
    id_type: BaseUserIDType.BASE_USER_ID_TYPE_UNSPECIFIED,
    id_code: '',
    avatar: '',
  })
  const [genderList, setGenderList] = useState<BaseDictForm_DictItem[]>([])
  const submittingRef = useRef(false)
  const navigateBackTimerRef = useRef<ReturnType<typeof setTimeout>>()
  const ensureAuthenticated = useUserStore((state) => state.ensureAuthenticated)
  const safeTop = Taro.getWindowInfo().safeArea?.top || 0
  const idTypeOptions = [
    { label: t('system.profile.id_type.unspecified'), value: BaseUserIDType.BASE_USER_ID_TYPE_UNSPECIFIED },
    { label: t('system.profile.id_type.id_card'), value: BaseUserIDType.BASE_USER_ID_TYPE_ID_CARD },
    { label: t('system.profile.id_type.passport'), value: BaseUserIDType.BASE_USER_ID_TYPE_PASSPORT },
    { label: t('system.profile.id_type.hk_macao_permit'), value: BaseUserIDType.BASE_USER_ID_TYPE_HK_MACAO_PERMIT },
    { label: t('system.profile.id_type.taiwan_permit'), value: BaseUserIDType.BASE_USER_ID_TYPE_TAIWAN_PERMIT },
    {
      label: t('system.profile.id_type.foreign_permanent_residence'),
      value: BaseUserIDType.BASE_USER_ID_TYPE_FOREIGN_PERMANENT_RESIDENCE,
    },
    { label: t('system.profile.id_type.other'), value: BaseUserIDType.BASE_USER_ID_TYPE_OTHER },
  ]
  const idTypeIndex = Math.max(0, idTypeOptions.findIndex((item) => item.value === userInfo.id_type))

  useEffect(() => {
    void Taro.setNavigationBarTitle({ title: t('system.profile.title') })
  }, [locale])

  useEffect(() => {
    return () => {
      if (navigateBackTimerRef.current) clearTimeout(navigateBackTimerRef.current)
    }
  }, [])

  const requireAuth = () => {
    if (ensureAuthenticated()) return true
    navigateToLogin()
    return false
  }

  const loadData = async () => {
    const [profile, gender] = await Promise.all([
      useUserStore.getState().getUserProfile(),
      defBaseDictService.GetBaseDict({ code: 'base_user_gender' }),
    ])
    setUserInfo(profile)
    setGenderList(gender.items || [])
  }

  useLoad(() => {
    if (requireAuth()) void loadData()
  })

  const uploadAvatar = async (filePath: string) => {
    if (!requireAuth()) return
    try {
      const fileInfo = await uploadFile('avatar', filePath)
      const nextProfile = { ...userInfo, avatar: fileInfo.url }
      await defAuthService.UpdateUserProfile({ user_profile: nextProfile })
      setUserInfo(nextProfile)
      await useUserStore.getState().getUserProfile()
      await Taro.showToast({ icon: 'success', title: t('system.profile.update_success') })
    } catch {
      await Taro.showToast({ icon: 'error', title: t('system.profile.avatar_upload_failed') })
    }
  }

  const onAvatarChange = async () => {
    if (!requireAuth()) return
    const selected =
      process.env.TARO_ENV === 'weapp'
        ? await Taro.chooseMedia({ count: 1, mediaType: ['image'] })
        : await Taro.chooseImage({ count: 1 })
    const file = selected.tempFiles[0]
    const filePath = 'tempFilePath' in file ? file.tempFilePath : file.path
    if (file.size > IMG_MAX_SIZE) {
      await Taro.showToast({ title: t('system.profile.photo_limit'), icon: 'none', duration: 1500 })
      return
    }
    await uploadAvatar(filePath)
  }

  const onGetPhoneNumber = async (event: { detail: { errMsg?: string; code?: string } }) => {
    if (event.detail.errMsg !== 'getPhoneNumber:ok' || !requireAuth()) return
    const response = await defAuthService.BindUserPhone({ code: event.detail.code || '' })
    setUserInfo((current) => ({ ...current, phone: response.phone }))
    await useUserStore.getState().getUserProfile()
    await Taro.showToast({ icon: 'success', title: t('system.profile.phone_authorization_success') })
  }

  const onSubmit = async () => {
    if (submittingRef.current) return
    if (!requireAuth()) return
    if (userInfo.email && !EMAIL_PATTERN.test(userInfo.email)) {
      await Taro.showToast({ icon: 'none', title: t('system.profile.email_invalid') })
      return
    }
    if (userInfo.id_code && !ID_CODE_PATTERN.test(userInfo.id_code)) {
      await Taro.showToast({ icon: 'none', title: t('system.profile.id_code_invalid') })
      return
    }
    submittingRef.current = true
    try {
      await defAuthService.UpdateUserProfile({ user_profile: userInfo })
      await useUserStore.getState().getUserProfile()
      await Taro.showToast({ icon: 'success', title: t('system.profile.save_success') })
      if (navigateBackTimerRef.current) clearTimeout(navigateBackTimerRef.current)
      navigateBackTimerRef.current = setTimeout(() => void Taro.navigateBack(), 400)
    } finally {
      submittingRef.current = false
    }
  }

  return (
    <View className='profile-viewport' style={{ backgroundImage: `url(${navigatorBackground})` }}>
      <View className='profile-navbar' style={{ paddingTop: `${safeTop}px` }}>
        <View className='profile-back' onClick={() => void Taro.navigateBack()}>‹</View>
        <View className='profile-navbar__title'>{t('system.profile.title')}</View>
      </View>
      <View className='profile-avatar'>
        <View className='profile-avatar__content' onClick={() => void onAvatarChange()}>
          <Image className='profile-avatar__image' src={userInfo.avatar ? formatSrc(userInfo.avatar) : defaultAvatar} mode='aspectFill' />
          <Text className='profile-avatar__text'>{t('system.profile.avatar_change')}</Text>
        </View>
      </View>
      <View className='profile-form'>
        <View className='profile-form__content'>
          {userInfo.user_name ? (
            <View className='profile-form__item'>
              <Text className='profile-label'>{t('system.profile.account')}</Text>
              <Text className='profile-account profile-placeholder'>{userInfo.user_name}</Text>
            </View>
          ) : null}
          {process.env.TARO_ENV === 'weapp' ? (
            <View className='profile-form__item'>
              <Text className='profile-label'>{t('system.profile.mobile')}</Text>
              <View className='profile-input'>
                {userInfo.phone ? (
                  <Text className='profile-account'>{userInfo.phone}</Text>
                ) : (
                  <Button className='profile-auth-button' openType='getPhoneNumber' onGetPhoneNumber={onGetPhoneNumber}>{t('system.profile.phone_authorization')}</Button>
                )}
              </View>
            </View>
          ) : null}
          <View className='profile-form__item'>
            <Text className='profile-label'>{t('system.profile.nick_name')}</Text>
            <Input className='profile-input' placeholder={t('system.profile.nick_name_placeholder')} value={userInfo.nick_name} onInput={(event) => setUserInfo((current) => ({ ...current, nick_name: event.detail.value }))} />
          </View>
          <View className='profile-form__item'>
            <Text className='profile-label'>{t('system.profile.email')}</Text>
            <Input className='profile-input' type='text' placeholder={t('system.profile.email_placeholder')} value={userInfo.email} onInput={(event) => setUserInfo((current) => ({ ...current, email: event.detail.value }))} />
          </View>
          <Picker
            mode='selector'
            range={idTypeOptions.map((item) => item.label)}
            value={idTypeIndex}
            onChange={(event) => setUserInfo((current) => ({ ...current, id_type: idTypeOptions[Number(event.detail.value)]?.value ?? BaseUserIDType.BASE_USER_ID_TYPE_UNSPECIFIED }))}
          >
            <View className='profile-form__item'>
              <Text className='profile-label'>{t('system.profile.id_type')}</Text>
              <Text className='profile-input profile-account'>{idTypeOptions[idTypeIndex]?.label}</Text>
            </View>
          </Picker>
          <View className='profile-form__item'>
            <Text className='profile-label'>{t('system.profile.id_code')}</Text>
            <Input className='profile-input' type='text' placeholder={t('system.profile.id_code_placeholder')} value={userInfo.id_code} onInput={(event) => setUserInfo((current) => ({ ...current, id_code: event.detail.value }))} />
          </View>
          <View className='profile-form__item'>
            <Text className='profile-label'>{t('system.profile.gender')}</Text>
            <RadioGroup onChange={(event) => setUserInfo((current) => ({ ...current, gender: Number(event.detail.value) }))}>
              {genderList.map((item) => (
                <Label className='profile-radio' key={item.value}>
                  <Radio value={item.value} color='#27ba9b' checked={userInfo.gender === Number(item.value)} />
                  {item.label}
                </Label>
              ))}
            </RadioGroup>
          </View>
        </View>
        <Button className='profile-form__button' onClick={() => void onSubmit()}>{t('common.action.save')}</Button>
      </View>
    </View>
  )
}
