// frontend/taro-app/packages/cli/templates/workspace/apps/taro-app/src/app.tsx
import type { PropsWithChildren } from 'react'
import { useDidHide, useDidShow, useLaunch } from '@tarojs/taro'
import { bootstrapKratosTaroApp } from '@liujitcn/kratos-taro-app-core'
import {
  pauseNotificationPolling,
  resumeNotificationPolling,
} from '@liujitcn/kratos-taro-app-system'
import { moduleManifest } from './module-manifest'
import './app.scss'

/** Taro 宿主根组件。 */
export default function App({ children }: PropsWithChildren) {
  useLaunch(() => {
    bootstrapKratosTaroApp({ modules: moduleManifest })
  })
  useDidShow(() => resumeNotificationPolling())
  useDidHide(() => pauseNotificationPolling())
  return children
}

// frontend/uni-app/apps/uni-app/src/App.vue
<script setup lang="ts">
import { onHide, onLaunch, onShow } from '@dcloudio/uni-app'
import {
  pauseNotificationPolling,
  resumeNotificationPolling,
  startNotificationPolling,
} from '@liujitcn/kratos-uni-app-system'

onLaunch(() => startNotificationPolling())
onShow(() => resumeNotificationPolling())
onHide(() => pauseNotificationPolling())
</script>

<style lang="scss">
@use '../../../packages/core/src/styles/base.scss';
</style>
