// frontend/taro-app/packages/core/src/views/pages/webview/webview.tsx
import { Button, Text, View, WebView } from '@tarojs/components'
import Taro, { useLoad } from '@tarojs/taro'
import { useEffect, useState } from 'react'
import './webview.scss'
import { useI18n } from '../../../locales'

/** 只放行 http(s) 外链，其它协议按非法地址处理。 */
const isAllowedUrl = (value: string) => /^https?:\/\//i.test(value)

const safeDecodeURIComponent = (value: string) => {
  try {
    return decodeURIComponent(value)
  } catch {
    return value
  }
}

/** 统一外链承载页。 */
export default function WebViewPage() {
  const { t } = useI18n()
  const [url, setUrl] = useState('')
  const [iframeLoaded, setIframeLoaded] = useState(false)
  const [iframeTimedOut, setIframeTimedOut] = useState(false)
  const isH5 = process.env.TARO_ENV === 'h5'

  useLoad((query) => {
    const nextUrl = safeDecodeURIComponent(query?.url || '')
    setUrl(isAllowedUrl(nextUrl) ? nextUrl : '')
    const title = safeDecodeURIComponent(query?.title || '')
    if (title) void Taro.setNavigationBarTitle({ title })
  })

  useEffect(() => {
    if (!isH5 || !url) return undefined
    setIframeLoaded(false)
    setIframeTimedOut(false)
    const timer = window.setTimeout(() => setIframeTimedOut(true), 800)
    return () => window.clearTimeout(timer)
  }, [isH5, url])

  const showFallback = !url || (isH5 && iframeTimedOut && !iframeLoaded)
  const emptyDescription = url
    ? t('core.webview.embed_blocked')
    : t('core.webview.invalid_url')

  return (
    <View className='webview-container'>
      {url ? (
        <WebView src={url} onLoad={() => setIframeLoaded(true)} />
      ) : null}
      {showFallback ? (
        <View className='webview-empty'>
          <Text className='webview-empty__title'>{t('core.webview.open_failed')}</Text>
          <Text className='webview-empty__desc'>{emptyDescription}</Text>
        </View>
      ) : null}
      {isH5 && url && iframeTimedOut ? (
        <Button
          className='webview-open-button'
          onClick={() => window.open(url, '_blank', 'noopener,noreferrer')}
        >
          {t('common.action.open_in_new_window')}
        </Button>
      ) : null}
    </View>
  )
}

// frontend/uni-app/packages/core/src/views/pages/webview/webview.vue
<template>
  <view class="webview-container">
    <!-- 小程序/APP 使用 web-view 组件 -->
    <!-- #ifdef MP-WEIXIN || MP-ALIPAY || APP-PLUS -->
    <web-view :src="url" @message="handleMessage"></web-view>
    <!-- #endif -->

    <!-- H5 直接跳转 -->
    <!-- #ifdef H5 -->
    <iframe
      v-if="isH5 && url"
      :src="url"
      frameborder="0"
      class="h5-iframe"
      @load="handleIframeLoad"
    ></iframe>
    <!-- #endif -->

    <view v-if="showFallback" class="webview-empty">
      <view class="webview-empty__title">{{ t('core.webview.open_failed') }}</view>
      <view class="webview-empty__desc">{{ emptyDesc }}</view>
    </view>

    <!-- #ifdef H5 -->
    <!-- X-Frame-Options 拒绝嵌入时浏览器仍可能触发 iframe load，始终保留外部打开入口。 -->
    <button v-if="isH5 && url && isIframeTimedOut" class="webview-open-button" @tap="openInBrowser">
      {{ t('common.action.open_in_new_window') }}
    </button>
    <!-- #endif -->
  </view>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { useI18n } from '../../../locales'

const url = ref('')
const isH5 = ref(false)
const isIframeLoaded = ref(false)
const isIframeTimedOut = ref(false)
const { t } = useI18n()

/** 只放行 http(s) 外链，其它协议按非法地址处理。 */
const isAllowedUrl = (value: string) => /^https?:\/\//i.test(value)

const safeDecodeURIComponent = (value: string) => {
  try {
    return decodeURIComponent(value)
  } catch {
    return value
  }
}

const showFallback = computed(
  () => !url.value || (isH5.value && isIframeTimedOut.value && !isIframeLoaded.value),
)
const emptyDesc = computed(() => {
  if (!url.value) {
    return t('core.webview.invalid_url')
  }
  return t('core.webview.embed_blocked')
})

onLoad((query) => {
  const nextUrl = safeDecodeURIComponent(query?.url || '')
  url.value = isAllowedUrl(nextUrl) ? nextUrl : ''
  const title = safeDecodeURIComponent(query?.title || '')
  // 调用方传入标题时同步更新原生导航栏，避免继续显示页面注册时的空标题。
  if (title) {
    void uni.setNavigationBarTitle({ title })
  }

  // #ifdef H5
  isH5.value = true
  // H5 iframe 可能被 X-Frame-Options 拦截，超时后展示明确兜底。
  window.setTimeout(() => {
    isIframeTimedOut.value = true
  }, 800)
  // #endif
})

/** 标记 H5 iframe 已完成加载，避免正常外链被兜底层遮挡。 */
const handleIframeLoad = () => {
  isIframeLoaded.value = true
}

/** H5 下外链被禁止嵌入时，允许用户用新窗口继续访问。 */
const openInBrowser = () => {
  if (!url.value) return
  // #ifdef H5
  window.open(url.value, '_blank', 'noopener,noreferrer')
  // #endif
}

// 小程序接收消息（第三方消息不落日志，避免敏感信息泄漏）。
const handleMessage = () => {}
</script>

<style scoped>
.webview-container {
  position: relative;
  flex: 1;
  height: 100vh;
}
.h5-iframe {
  width: 100%;
  height: 100vh;
}

.webview-empty {
  position: absolute;
  inset: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 48rpx;
  text-align: center;
  background-color: #fff;
}

.webview-empty__title {
  font-size: 32rpx;
  font-weight: 600;
  color: #333;
}

.webview-empty__desc {
  margin-top: 16rpx;
  font-size: 26rpx;
  color: #888;
}

.webview-open-button {
  position: fixed;
  right: 24rpx;
  bottom: 96rpx;
  z-index: 2;
  width: 240rpx;
  height: 72rpx;
  line-height: 72rpx;
  border-radius: 72rpx;
  background-color: #27ba9b;
  color: #fff;
  font-size: 26rpx;
}
</style>
